"""Mock AI provider (Phase 8).

Used whenever no ``OPENAI_API_KEY`` is configured (local dev, CI, the
Phase 8 audit). It produces a deterministic, context-aware reply so the
*entire* runtime — persistence, streaming, token tracking, title
generation, KB injection — can be exercised end-to-end without a paid
API or network access.
"""
from __future__ import annotations

import asyncio
from typing import AsyncIterator

from app.providers.base import (
    AIProvider,
    AIResponse,
    ChatMessage,
    TokenUsage,
    estimate_tokens,
)


class MockProvider(AIProvider):
    name = "mock"

    def _compose(self, messages: list[ChatMessage]) -> str:
        last_user = next(
            (m.content for m in reversed(messages) if m.role == "user"),
            "",
        )
        has_context = any("CONTEXT:" in m.content for m in messages if m.role == "system")
        snippet = (last_user or "").strip()
        if len(snippet) > 160:
            snippet = snippet[:160] + "…"
        grounded = " Based on the knowledge available to me," if has_context else ""
        return (
            f"{grounded} here's what I can tell you about \"{snippet}\". "
            "This is a simulated assistant response generated by the OraOne "
            "runtime because no live model provider is configured. Once an "
            "OPENAI_API_KEY is set, real GPT responses will appear here."
        ).strip()

    async def chat(
        self,
        messages: list[ChatMessage],
        *,
        model: str,
        temperature: float = 0.7,
        max_tokens: int = 1024,
    ) -> AIResponse:
        content = self._compose(messages)
        prompt_tokens = sum(estimate_tokens(m.content) for m in messages)
        completion_tokens = estimate_tokens(content)
        return AIResponse(
            content=content,
            model=f"mock:{model}",
            usage=TokenUsage(
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
                total_tokens=prompt_tokens + completion_tokens,
            ),
            finish_reason="stop",
        )

    async def stream(
        self,
        messages: list[ChatMessage],
        *,
        model: str,
        temperature: float = 0.7,
        max_tokens: int = 1024,
    ) -> AsyncIterator[str]:
        content = self._compose(messages)
        # Emit word-by-word so the SSE pipeline is genuinely incremental.
        for i, word in enumerate(content.split(" ")):
            chunk = word if i == 0 else " " + word
            await asyncio.sleep(0)  # cooperative yield — keeps it cancel-safe
            yield chunk
